config/routes.rb
Diploma::Application.routes.draw do
  devise_for :users

  root to: 'static#dashboard'

  resources :users do
    member do
      get :block
      get :unblock
      get :list_tasks
      get :show_statistics
    end
    collection do
      post :blocked
      get :blocked
    end
    resources :weekly_surveys
  end

  resources :projects do
  end
  resources :tasks

  #resources :project_montly_incomes
  delete 'users/:id/delete_avatar', to: 'users#delete_avatar', as: :delete_avatar
  delete 'projects/:id/delete_logo', to: 'project#delete_logo', as: :delete_logo
  patch 'task/:id/change_status', to: 'tasks#change_status', as: :change_status
  get 'blocked', to: 'static#blocked', as: :blocked
  get 'task_assign_adviser', to: 'static#task_adviser', as: :task_adviser
end

app/models/task.rb
class Task < ActiveRecord::Base

	# associations
	belongs_to :user
	belongs_to :project
  has_many :action_logs

	#attributes accessibility
	attr_accessible :name, :user_id, :project_id, :description, :real_time,
					        :status, :full_description, :specialization, :deadline

	TASK_STATUSES = [DEFAULT_STATUS =  "just created", CANCELLED = 'dismissed',
                   IN_PROGRESS = "in progress", DONE = "done",
                   PAUSED = 'paused']
  TASK_SPECIALIZATIONS = %w(content server_side script_writing UI_UX testing GA SEO)
	# validations
	validates :name, presence: true, uniqueness: true
	validates :project_id, presence: true, inclusion: { in: Project.pluck(:id) }
	validates :status, inclusion: { in: TASK_STATUSES }
  validates :description, presence: true, length: { maximum: 100 }
  validates :full_description, presence: true, length: { maximum: 800 }
  validates :specialization, presence: true, inclusion: { in: TASK_SPECIALIZATIONS }
  validates :deadline, presence: true

	after_initialize :set_default_state
  before_save :nil_if_blank

  scope :active, ->{ where status: TASK_STATUSES.except('dissmissed') }
  scope :dismissed, ->{ where status: 'dismissed' }
  scope :finished, ->{ where status: 'done' }
  scope :still_open, ->{ where status: [IN_PROGRESS, DEFAULT_STATUS, PAUSED] }
  scope :last_30_days, proc { |period| where created_at: (Time.now - 30.days)..Time.now }
  scope :started_this_month, -> { where created_at: Time.now.beginning_of_month..Time.now.end_of_month }
  scope :with_no_user, -> { where user_id: nil }
  scope :not_resolved, ->{ where('status = ? or status = ?', DEFAULT_STATUS, IN_PROGRESS) }

  [:just_created, :in_progress, :done, :dismissed, :paused].each do |in_status|
    define_method in_status do
      status == in_status.to_s.humanize.downcase
    end
  end


  def log_action(user, action, msg = '')
    action_logs.create! do |e|
      e.user = user
      e.project = project
      e.action = action
      e.data = msg
    end
  end

  def has_no_user
    !user
  end

  def time_left
    if started_at && status == IN_PROGRESS
      (started_at + 3*3600 + deadline.hour*3600 + deadline.min*60 - Time.now.hour*3600 - Time.now.min*60).time
     else
      deadline
    end
  end

	private
	def set_default_state
		self.status ||= DEFAULT_STATUS
	end

  def nil_if_blank
    [:user_id, :project_id].each { |attr| self[attr] = nil if self[attr].blank? }
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :load_task, only: [:show, :edit, :update, :destroy, :change_status]


  def index
    @user = current_user
    @tasks = if params[:project_id]
      @project = Project.find params[:project_id]
      Project.find(params[:project_id]).tasks
    else
      Task.all.order('name ASC')
    end
  end

  def show
    @user = current_user
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new params[:task]
    if @task.save
      log_task @task, :created_task
      log_task @task, :assigned, " to #{@task.user.naming}" unless @task.user.nil?
      flash[:notice] = "Successfuly created"
      render :show
    else
      flash[:error] = "Error/s occured while creating"
      render :new
    end
  end

  def edit
  end

  def update
    prev_owner = @task.user
    @task.update_attributes params[:task]
    if @task.save
      new_owner = @task.user
      log_task @task, :updated_task
      log_task @task, :assigned, " to #{@task.user.naming}" if (prev_owner != new_owner)
      flash[:notice] = "Successfuly updated"
      render :show
    else
      flash[:error] = "Error/s occured while updating"
      render :edit
    end
  end

  def destroy
    name = @task.name
    @task.update_attribute :status, 'dismissed'
    log_task @task, :dismissed
    redirect_to tasks_path
  end

  def change_status
    case params[:status]
    when 'start'
      log_task @task, :started
      @task.update_attribute :started_at, DateTime.now
      @task.update_attribute :status, Task::IN_PROGRESS
    when 'finish'
      log_task @task, :done
      @task.update_attribute :real_time, (Time.now - @task.started_at.time.hour*3600 - @task.started_at.min*60)
      @task.update_attribute :deadline, @task.time_left
      @task.update_attribute :status, Task::DONE
    when 'dismiss'
      log_task @task, :stopped_progress
      @task.update_attribute :status, Task::CANCELLED
      @task.update_attribute :user_id, nil
      @task.update_attribute :real_time, nil
    when 'activate'
      log_task @task, :activated
      @task.update_attribute :status, Task::DEFAULT_STATUS
    when 'pause'
      @task.update_attribute :deadline, @task.time_left
      @task.update_attribute :real_time, (Time.now - @task.started_at.time.hour*3600 - @task.started_at.min*60)
      @task.update_attribute :status, Task::PAUSED
    when 'continue'
      @task.update_attribute :status, Task::IN_PROGRESS
    end
    redirect_to task_path @task
  end

  private
  def load_task
    @task = Task.find params[:id]
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_task_form.html.erb
<div class="panel-body">
  <div class="col-md-3">
    <%= simple_form_for @task do |f| %>
      <%= f.error_notification %>
      <%= f.input :name, required: true %>
      <%= f.association :project, as: :select, required: true %>
      <%= f.input :description, as: :text, required: true, maxlength: 250 %>
      <%= f.input :full_description, as: :text, required: true, maxlength: 800 %>
      <%= f.input :deadline, required: true, selected: f.object.try(:deadline) %>
      <%= f.input :priority, as: :select, collection: %w(urgent high low avarage), required: true, selected: f.object.try(:priority) %>
      <p class='help-block'><small>Time in hours for the issue to be resolved</small></p>
      <%= f.input :specialization, as: :select, collection: Task::TASK_SPECIALIZATIONS.map {|s| [s.humanize, s]}, required: true %>
      <br \>
      Assign user&nbsp;<input type="checkbox" id="user-assign-flag">
      <div id="user-assign">
        <%= f.association :user, as: :select, label_method: :naming, value_method: :id  %>
      </div>
      <br \>
      <br \>
      <%= f.button :submit, class: 'btn-primary' %>
      <button class="btn cancel-new-form btn-danger">Cancel</button>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <ol class="breadcrumb">
      <li><%= link_to 'Dashboard', root_path %></li>
      <li><%= link_to @task.project.name, project_path(@task.project) %></li>
      <li class="active">Edit <%= @task.name %></li>
    </ol>
  </div>
  <%= render 'task_form'%>
</div>

app/views/tasks/index.html.erb
<dl class="dl-horizontal panel panel-primary">
  <div class="panel-heading">Tasks</div>
  <div class="panel-body">
    <%= link_to '+ new task', new_task_path, class: 'btn add-new-item' %>
    <%= button_tag 'Show resolved issues', class: 'btn btn-danger hide-resolved add-new-item' %>
    <h2><%= @project.name + " task list" if defined? @project%></h2>
    <br \>
    <% if @tasks.any? %>
      <table class="table table-hover table-striped" id="tasks-table">
        <th>Identical name</th>
        <th>Project</th>
        <th>Description</th>
        <th>Assigned user</th>
        <th>Status</th>
        <th>Actions</th>
        <% @tasks.each do |task| %>
            <tr class='<%= if task.done then 'success' end %>'>
              <td><%= link_to task.name, task_path(task) %></td>
              <td><%= task.project.name %></td>
              <td><%= task.description ? task.description : '-' %></td>
              <td>
                <% if task.user %>
                  <%= link_to task.user.name || task.user.nickname, user_path(task.user.id) %>
                <% else %>
                  <%= link_to "Assing user", "#"%>
                <% end %>
              </td>
              <td><%= task.status %></td>
              <td><%= link_to_unless(task.done, "edit", edit_task_path(task)){} %>
              <br \>
              <%= link_to_if((task.just_created || task.in_progress) ,'stop progress', task, :confirm => 'Are you sure?', :method => :delete){} %></td>
            </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</dl>

app/views/tasks/new.html.erb
<div class="panel panel-primary">
    <div class="panel-heading">
    <ol class="breadcrumb">
      <li><%= link_to 'Dashboard', root_path %></li>
      <li><%= link_to 'Tasks', tasks_path %></li>
      <li class="active">New task</li>
    </ol>
  </div>
  <%= render 'task_form'%>
</div>

app/views/tasks/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <div class="media">
      <% url = @task.project.logo.exists? ? @task.project.logo.url(:thumb) : 'original/no-logo.png' %>
      <%= image_tag url, size: "100x100", alt: "NO logo", class: "img-responsive pull-left media-object" %>
      <div class="media-body">
        <ol class="breadcrumb">
          <li><%= link_to 'Dashboard', root_path %></li>
          <li><%= link_to 'Projects', projects_path %></li>
          <li><%= link_to @task.project.name, project_path(@task.project) %></li>
          <li class="active"><%= @task.name %></li>
          <%= render partial: 'shared/task_buttons', locals: { task: @task } %>
        </ol>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="col-md-6">
      <ul class="list-group">
        <li class="list-group-item">
          <h4 class="list-group-item-heading">Stastus</h4>
          <div class="media">
            <div class="media-body">
              <p><%= @task.status  %></p>
            </div>
          </div>
        </li>
        <li class="list-group-item">
          <h4 class="list-group-item-heading">Short description</h4>
          <div class="media">
            <div class="media-body">
              <p><%= @task.description  %></p>
            </div>
          </div>
        </li>
        <li class="list-group-item">
          <h4 class="list-group-item-heading">Full description</h4>
          <div class="media">
            <div class="media-body">
              <p><%= simple_format(@task.full_description) %></p>
            </div>
          </div>
        </li>
      </ul>
    </div>
    <div class="col-md-6">
      <div class="list-group">
        <div class="list-group-item">
          <h4 class="list-group-item-heading">Assignee</h4>
          <% if @task.user %>
            <p class="list-group-item-text"><%= link_to @task.user.naming, user_path(@task.user) %></p>
            <% elsif @task.dismissed %>
              <% dismissed_by = User.find(@task.action_logs.where(action: 'stopped_progress').last.user_id)%>
              <p class="list-group-item-text">Dismissed by <%= link_to dismissed_by.naming, user_path(dismissed_by) %></p>
          <% end %>
        </div>
      </div>
      <div class="list-group">
        <div class="list-group-item">
          <h4 class="list-group-item-heading">Dates</h4>
          <div class="list-group-item-text">
            <dl class="dl-horizontal">
              <dt>Created at: </dt>
              <dd><%= @task.created_at.strftime('%d/%m/%Y at %I:%M%p') %></dd>
              <dt>Updated at: </dt>
              <dd><%= @task.updated_at.strftime('%d/%m/%Y at %I:%M%p') %></dd>
              <dt class="text-danger">Time left: </dt>
              <dd>
                <%= @task.time_left.strftime('%H:%M')%>
                </dd>
              <dt>Time spent: </dt>
              <dd><%= @task.real_time? ? @task.real_time.strftime('%H:%M') : '-' %></dd>
              </dl>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>