config/routes.rb
Diploma::Application.routes.draw do
  devise_for :users

  root to: 'static#dashboard'

  resources :users do
    member do
      get :block
      get :unblock
      get :list_tasks
      get :show_statistics
    end
    collection do
      post :blocked
      get :blocked
    end
    resources :weekly_surveys
  end

  resources :projects do
  end
  resources :tasks

  #resources :project_montly_incomes
  delete 'users/:id/delete_avatar', to: 'users#delete_avatar', as: :delete_avatar
  delete 'projects/:id/delete_logo', to: 'project#delete_logo', as: :delete_logo
  patch 'task/:id/change_status', to: 'tasks#change_status', as: :change_status
  get 'blocked', to: 'static#blocked', as: :blocked
  get 'task_assign_adviser', to: 'static#task_adviser', as: :task_adviser
end

app/models/user.rb
class User < ActiveRecord::Base
	include ActiveModel::Validations

  # default devise modules
  devise :database_authenticatable, :registerable,
         :trackable, :validatable
	# associations
  has_many :projects, through: :tasks
	has_many :tasks, dependent: :delete_all
  has_many :action_logs, dependent: :delete_all

	# attribute accessibility
	attr_accessible :name, :nickname, :email, :role, :position, :salary_per_hour,
					:level, :weekly_surveys_attributes, :password, :active, :avatar

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>", :small => "40x40>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	accepts_nested_attributes_for :tasks

	# constants
  USER_ACTIVE_STATUSES = [ACTIVE = "active", BLOCKED = "blocked"]
	USER_ROLES = [DEFAULT_ROLE = 'user', MANAGER = 'manager', ADMIN = 'admin']
	USER_WORK_LEVELS = %w(junior middle senior)
	USER_SPECIALIZATIONS = ['tester', 'back-end developer', 'front-end developer', 'SEO', 'content manager']
  ATTRIBUTES_TO_SCRUB = %w(id created_at updated_at encrypted_password sign_in_count
                          current_sign_in_at last_sign_in_at current_sign_in_ip last_sign_in_ip
                          password avatar_file_name avatar_content_type avatar_file_size
                          avatar_updated_at)

	# validations
	validates :name, presence:true, uniqueness: true, length: { maximum: 100 }, on: :update
  validates :email, presence: true, uniqueness: true
  validates :role, presence: true, inclusion: { in: USER_ROLES }, on: :update
  validates :salary_per_hour, presence: true, numericality: true, inclusion: { in: (1..100) }, on: :update
  validates :level, presence: true, inclusion: { in: USER_WORK_LEVELS }, on: :update
  validates :position, presence: true, inclusion: { in: USER_SPECIALIZATIONS }, on: :update

  before_save :set_default_settings
  after_initialize :set_active, on: :create

  scope :active, -> { where(:active => ACTIVE) }
  scope :blocked, -> { where(:active => BLOCKED) }

  def admin?
  	role == ADMIN
  end

  def manager?
  	role == MANAGER
  end

  def active?
    active == ACTIVE
  end

  def new_tasks
    tasks ? tasks.where('status = ?', Task::DEFAULT_STATUS) : []
  end

  def new_tasks_counter
    tasks ? new_tasks.count : 0
  end

  #def projects
    #ids = Task.where('user_id = ? ', id).pluck(:project_id)
    #Project.find(ids)
  #end

  def naming
    name || nickname
  end

  def started_this_month_tasks
    tasks.started_this_month
  end

  def general_month_time
    started_this_month_tasks.finished.pluck(:real_time).inject do |total_time, time|
      total_time + time.hour*3600 + time.min*60
    end
  end

  def calculate_salary
    if salary_per_hour
      salary_per_minute = salary_per_hour.to_f/60
      general_month_time.hour*salary_per_hour + general_month_time.min*salary_per_minute
    end
  end

  private
  def set_default_settings
  	self.role ||= DEFAULT_ROLE
  	self.nickname ||= email.split('@')[0]
  end

  def set_active
    self.active ||= ACTIVE
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_user, except: [:index]


	def index
		@users = User.active.order('last_sign_in_at DESC')
    @user = current_user
	end

	def show
    @action_logs = ActionLog.for_user(@user).first(15)
	end

	def edit
	end

  def update
    params[:user].delete(:password) if params[:user][:password].blank?
    @user.update_attributes params[:user]
    if @user.save
      redirect_to user_path(@user), notice: "Successfuly updated"
    else
      render :edit
    end
  end

  def block
    @user.update_attribute :active, User::BLOCKED
    respond_to do |format|
      format.html { redirect_to users_path }
      format.js   { render nothing: true }
    end
  end

  def unblock
    @user.update_attribute :active, User::ACTIVE
    respond_to do |format|
      format.html { redirect_to blocked_users_path }
      format.js   { render nothing: true }
    end
  end

  def blocked
    @users = User.blocked.order('last_sign_in_at DESC')
  end

  def list_tasks
    if params.include?(:project_id)
      @tasks =  @user.tasks.where(project_id: params[:project_id])
      @project = Project.find params[:project_id]
    else
      @tasks = @user.tasks
    end
  end

  def show_statistics
    @tasks = @user.tasks.started_this_month
    @projects = Project.where(id: @tasks.pluck(:project_id))
    dismissed = ActionLog.where(user_id: @user.id, action: :stopped_progress)
    @dismissed = dismissed ? dismissed.count : 0
  end

  def delete_avatar
    @user.avatar.destroy
    redirect_to user_path @user
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_info.html.erb
<div class="row"></div>
<% user.attributes.except(* User::ATTRIBUTES_TO_SCRUB).each_pair do |name, value| %>
  <dt><%= name.humanize %></dt>
  <dd><%= name == 'email' ? mail_to(value) : value %><%='$' if name == 'salary_per_hour' %></dd>
<% end %>

app/views/users/_user_photo.html.erb
 <div class="col-md-6 col-md-offset-3">
  <% @url = user.avatar.exists? ? user.avatar.url(:thumb) : 'original/missing.png' %>
  <%= image_tag @url, size: '100x100', class: "img-responsive img-thumbnail", alt: "Avatar" %>
</div>

app/views/users/_users_table.html.erb
  <table class="table table-hover" id="users-table">
    <th>Email</th>
    <th>Name/Nickname</th>
    <th>Last logged in</th>
    <th>Actions</th>
    <% @users.each do |user| %>
        <tr class="<%= current_user == user ? 'success user-raw' : 'user-raw' %>">
          <td><%= link_to user.email, user_path(user), target: '_blank' %></td>
          <td><%= user.name ? user.name : user.nickname %></td>
          <td><%= user.last_sign_in_at.strftime('%d/%m/%Y at %I:%M%p') %></td>
          <td>
            <div style="display: inline-flex;">
              <% if current_user == user %>
                <%= link_to 'edit', edit_user_path(user.id), class: 'btn btn-success btn-sm' %>
              <% elsif current_user.admin? %>
                <%= link_to_if(user.active?, 'block', block_user_path(user.id), remote: true, class: 'delete-from-table btn btn-danger btn-sm'){link_to 'unblock',unblock_user_path(user.id), remote: true, class: 'delete-from-table btn btn-success btn-sm'} %>
              <% end %>
              <% if user.tasks.any? %>
                <%= link_to "list tasks", list_tasks_user_path(user), class: 'btn btn-default btn-sm' %>
              <% end %>
            </div>
          </td>
        </tr>
    <% end %>
  </table>

app/views/users/blocked.html.erb
<dl class="dl-horizontal panel panel-primary">
  <div class="panel-heading">Users</div>
  <div class="panel-body">
    <%= link_to 'List active users', users_path, class: 'btn btn-lrg btn-default btn-inverse' %>&nbsp;<small>(so you can block them)</small></p>
    <%= render 'users_table' if @users.any? %>
  </div>
</dl>

app/views/users/edit.html.erb
<dl class="dl-horizontal panel panel-primary">
  <div class="panel-heading"><%= render 'shared/profile_sticked' %></div>
  <div class="panel-body">
    <div class="col-md-6">
      <div class="panel panel-black">
        <div class="panel-heading">Upload your avatar</div>
        <div class="panel-body">
          <%= simple_form_for @user, :html => { :multipart => true } do |f| %>
            <% url = @user.avatar.exists? ? @user.avatar.url(:medium) : 'original/missing.png' %>
            <%= image_tag url, size: "300x300", alt: "NO avatar", class: "img-thumbnail" %>
            <div class="input-group">
              <span class="btn btn-default btn-file">
                <%= f.file_field :avatar %>
              </span>
            </div>
            <p class="help-block">*Maximum resoution 300x300</p>
            <%= link_to_if(@user.avatar.exists?, 'Delete avatar', delete_avatar_path(@user), class: 'btn btn-danger', method: :delete){}%>
        </div>
      </div>
    </div>
    <div class="col-md-6 pull-right well">
        <%= f.error_notification %>
          <%= f.input :name, required: true %>
          <%= f.input :email, placeholder: @user.email, as: :email, required: true %>
          <%= f.input :nickname, placeholder: @user.nickname %>
          <%= f.input :password, placeholder: 'change password..', as: :password %>
          <p class="help-block">*If changed - need to reassign</p>
          <%= f.input :role, disabled: (current_user.admin? ? false : true), as: :select, collection: User::USER_ROLES, required: true %>
          <%= f.input :salary_per_hour, disabled: (current_user.admin? || current_user.manager? ? false : true), as: :decimal, :hint => "salary in $" %>
          <%= f.input :level, disabled: (current_user.admin? || current_user.manager? ? false : true), as: :select, collection: User::USER_WORK_LEVELS, required: true %>
          <%= f.input :position, disabled: (current_user.admin? || current_user.manager? ? false : true), as: :select, collection: User::USER_SPECIALIZATIONS, required: true %>
          <br \>
        <%= f.button :submit, "Submit changes", class: 'btn btn-primary' %>
        <%= link_to 'Cancel', users_path, class: 'btn btn-danger'%>
      <% end %>
    </div>
  </div>
</dl>

app/views/users/index.html.erb
<dl class="dl-horizontal panel panel-primary">
  <div class="panel-heading">Users</div>
  <div class="panel-body">
    <%= button_to "List blocked users", blocked_users_path, class: "btn btn-lrg btn-danger", id: 'blocked-users-button' %>
      <br \>
    <% if @users.active.any? && (current_user.admin? || current_user.manager?) %>
      <%= render 'users_table' %>
    <% end %>
  </div>
</dl>

app/views/users/list_tasks.html.erb
<dl class="dl-horizontal panel panel-primary">
  <div class="panel-heading">
    <h4><u><%= @project.name + ': ' if @project %></u>Tasks</h4>
    <div><%= @user.name || @user.nickname %></div>
    <hr>
    <%= button_tag 'Show resolved issues', class: 'btn btn-danger hide-resolved add-new-item' %>
  </div>
  <div class="panel-body">
    <div class="col-md-8">
      <% if @tasks.any? %>
        <table class='table table-hover'>
          <th>#</th>
          <th>Short description</th>
          <th>Project</th>
          <th>Status</th>
          <% @tasks.order('updated_at DESC').each do |t| %>
            <tr class="<%= 'success' if t.done  %>">
              <td><%= link_to t.name, task_path(t) %></td>
              <td><%= t.description %></td>
              <td><%= link_to t.project.name, project_path(t.project) %></td>
              <td><%= t.status.humanize %></td>
            </tr>
          <% end %>
        </table>
      <% else %>
        <blockquote>No tasks for the moment</blockquote>
      <% end %>
    </div>
  </div>
</dl>

app/views/users/show.html.erb
<dl class="dl-horizontal panel panel-primary">
  <div class="panel-heading"><%= render 'shared/profile_sticked' %></div>
  <div class="panel-body show-user-panel">
    <div class="col-md-6">
      <dl class="dl-horizontal panel panel-black">
        <div class="panel-heading">Summary details</div>
        <div class="panel-body">
          <%= render partial: 'user_photo', locals: { user: @user } %>
          <%= render partial: 'user_info', locals: { user: @user } %>
        </div>
      </dl>
      <dl class="dl-horizontal panel panel-black">
        <div class="panel-heading">Assigned Open/Resolved Issues per Project</div>
        <div class="panel-body">
          <% @user.projects.uniq.each do |p| %>
            <dt><%= link_to p.name, project_path(p) %></dt>
            <dd><%= link_to p.tasks.where('user_id =?', @user.id).count, list_tasks_user_path(@user, project_id: p.id) %></dd>
          <% end %>
        </div>
      </dl>
    </div>
    <div class="col-md-6">
      <dl class="dl-horizontal panel panel-warning">
        <div class="panel-heading">Activity Stream <small>(last 5)</small></div>
        <div class="panel-body">
          <ul class="list-group">
            <% if @action_logs.any? %>
              <% @action_logs.last(5).each do |log| %>
                <li class="list-group-item"><%= render partial: 'shared/action_log_box', locals: {action_log: log} %></li>
              <% end %>
              <%= link_to_if(@action_logs.size > 5, '<< Load more >>', "#", class: 'btn btn-warning btn-sm user-assign', style: 'width:100%;background-color:#e6a600 !important'){}%>
              <% else %>
              <p>Nothing happened</p>
            <% end %>
          </ul>
        </div>
      </dl>
       <dl class="dl-horizontal panel panel-warning">
        <div class="panel-heading">Salary per <%= current_month %></div>
        <div class="panel-body">
          <ul class="list-group">
            <% if @user.started_this_month_tasks.any? && @user.general_month_time %>
              <p>Total time: <%= @user.general_month_time.strftime('%H:%M') %></p>
               <p>Salary: <%= @user.calculate_salary %>$</p>
            <% else %>
              <p>Work more!</p>
            <% end %>
          </ul>
        </div>
      </dl>
    </div>
  </div>
</dl>

app/views/users/show_statistics.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3><%= link_to @user.naming, user_path(@user), class: 'text-info', style: "color:#fffefa !important;" %></h3>
  </div>
  <div class="panel-body">
    <dl class="dl-horizontal well">
      <%= render partial: 'user_info', locals: { user: @user } %>
    </dl>
    <div class="panel panel-primary">
      <div class="panel-heading">Tasks</div>
      <div class='panel-body'>
        <div class="col-md-6 ">
          <div class='container'>
            <h3 text-class="danger">TASKS</h3>
            <hr>
            <dl class="dl-horizontal col-md-6">
              <h4 text-class="danger">All time</h4>
              <hr>
              <dt>Started: </dt>
              <dd><%= link_to @user.tasks.count, list_tasks_user_path(@user) %></dd>
              <dt>Finished: </dt>
              <dd><%= link_to @user.tasks.finished.count, list_tasks_user_path(@user, finished: true) %></dd>
              <dt>Cancelled: </dt>
              <dd><%= link_to @user.tasks.dismissed.count %></dd>
            </dl>
            <dl class="dl-horizontal col-md-6">
              <h4 text-class="danger"><%= current_month %><small>(current month)</small></h4>
              <hr>
              <dt>Started: </dt>
              <dd><%= link_to @user.started_this_month_tasks.count, list_tasks_user_path(@user, finished: true, month: DateTime.now.month)%></dd>
              <dt>Finished: </dt>
              <dd><%= link_to @user.started_this_month_tasks.finished.count, list_tasks_user_path(@user, dismissed: true, month: DateTime.now.month) %></dd>
              <dt>Cancelled: </dt>
              <dd><%= link_to @user.started_this_month_tasks.dismissed.count %></dd>
            </dl>
          </div>
        </div>
        <div class='col-md-6'>
          <div>
            <%= render partial: 'shared/statistics_graph', locals: { title: 'All time', opened: @tasks.still_open.count, resolved: @tasks.finished.count, dismissed: @dismissed, id: "@user.naming-show-all-tasks" } %>
          </div>
          <div>
            <%= render partial: 'shared/statistics_graph', locals: { title: 'Last month', opened: @tasks.started_this_month.still_open.count, resolved: @tasks.started_this_month.finished.count, dismissed: @dismissed, id: "#{@user.naming}-show-tasks-last-month" } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>