config/routes.rb
Diploma::Application.routes.draw do
  devise_for :users

  root to: 'static#dashboard'

  resources :users do
    member do
      get :block
      get :unblock
      get :list_tasks
      get :show_statistics
    end
    collection do
      post :blocked
      get :blocked
    end
    resources :weekly_surveys
  end

  resources :projects do
  end
  resources :tasks

  #resources :project_montly_incomes
  delete 'users/:id/delete_avatar', to: 'users#delete_avatar', as: :delete_avatar
  delete 'projects/:id/delete_logo', to: 'project#delete_logo', as: :delete_logo
  patch 'task/:id/change_status', to: 'tasks#change_status', as: :change_status
  get 'blocked', to: 'static#blocked', as: :blocked
  get 'task_assign_adviser', to: 'static#task_adviser', as: :task_adviser
end

app/views/shared/_action_log_box.html.erb
<div class="media">
  <a class="pull-left" href="<%= user_path(action_log.user) %>">
    <% url = action_log.user.avatar.exists? ? action_log.user.avatar.url : 'original/missing.png' %>
    <%= image_tag url, size: "40x40", alt: "No avatar", class: "img-responsive pull-left media-object" %>
  </a>
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to action_log.user.naming, user_path(action_log.user) %>
      <% if action_log.task_id.nil? %>
        <%= ' ' + action_log.action.humanize.downcase + ' ' %>
        <%= link_to action_log.project.name, project_path(action_log.project) %>
        <%= ' ' + action_log.try(:data) %>
      <% else %>
        <%= ' ' + action_log.action.humanize.downcase + ' ' %>
        <%= link_to action_log.task.name, task_path(action_log.task) %>
        <%= ' ' + action_log.try(:data) %>
      <% end %>
    </h4>
    <%= action_log.created_at.strftime('%d/%m/%Y at %I:%M%p') %>, <%= link_to action_log.project.name, project_path(action_log.project)%>
  </div>
</div>

app/views/shared/_common_nav_bar.html.erb
<body>
  <nav class="navbar navbar-default navbar-inverse" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div id="header-logo">
          <%= image_tag("logo.png", size: "40x40", alt: "Logo")%>
          <%= link_to 'TimeTracker', root_path, class: 'navbar-brand' %>
        </div>
      </div>

      <% if current_user && current_user.active? %>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle hidden" data-toggle="dropdown">Statistics <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#">User statistics</a></li>
              <li><a href="#">Projects statistics</a></li>
              <li class="divider"></li>
              <li><a href="#">Action logs</a></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to_unless((current_user.role=='user'), "Assign Adviser", task_adviser_path) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle<%= ' hidden' if current_user.role == 'user' %>" data-toggle="dropdown">Admin resources <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Projects", projects_path %></li>
              <li><%= link_to "Tasks", tasks_path %></li>
              <li role="presentation" class="divider"></li>
              <li role="presentation" class="dropdown-header">Users</li>
              <li><%= link_to "Active users", users_path %></li>
              <li><%= link_to "Blocked users", blocked_users_path %></li>
            </ul>
          </li>
          <li>
            <% @url = current_user.avatar.exists? ? current_user.avatar.url(:thumb) : 'original/missing.png' %>
            <%= image_tag @url, size: '40', class: "img-responsive", alt: "Avatar", style: 'margin-top:4px;' %>
          </li>
          <li>
            <%= link_to current_user.naming, user_path(current_user.id) %>
          </li>
          <li><a href="<%= list_tasks_user_path(current_user) %>">New tasks <span class="badge"><%= current_user.new_tasks_counter %></span></a></li>
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
      <% end %>
    </div><!-- /.container-fluid -->
  </nav>
</body>

app/views/shared/_income_graph.html.erb
<div class="container"><canvas id='<%= "#{id}" %>' width='400' height='300'></canvas></div>
<script>
$(document).ready(function() {
  var g = new Bluff.Bar('<%= j id %>', '400x300');
  g.title = '<%= j title %>';
  g.minimum_value = 0;
  g.maximum_value = 50000;
  no_data_message = 'No data';
  g.theme_pastel();
  g.set_background({colors: '#323a47'});
  g.font_color = '#fffefa';
  g.marker_color = '#fffefa';



  g.data("Income", <%= incomes %>, '#3498db');
  g.data("Expense", <%= expenses %>,'#e74c3c');
  g.data("Profit", <%= profit %>,'#27ae60');
  g.labels = { 12: "<%= month_hash[0] if month_hash[0] %>",
               10: "<%= month_hash[2] if month_hash[2] %>",
               8: "<%= month_hash[4] if month_hash[4] %>",
               6: "<%= month_hash[6] if month_hash[6] %>",
               4: "<%= month_hash[8] if month_hash[8] %>",
               2: "<%= month_hash[10] if month_hash[10] %>",
               0: "<%= month_hash[12] if month_hash[12] %>"};
  g.draw();
})
</script>

app/views/shared/_profile_sticked.html.erb
<h3>
Profile: <%= @user.name || @user.nickname %>
</h3>
<p>
  <%= link_to_if(can_edit(@user), 'Edit', edit_user_path(@user), class: 'btn add-new-item'){} %>
  <%= link_to 'show statistics', show_statistics_user_path(@user), class: 'btn add-new-item' %>
</p>

app/views/shared/_statistics_graph.html.erb
<div class="container"><canvas id='<%= "#{id}" %>' width='400' height='300'></canvas></div>
<script>
$(document).ready(function() {
  var g = new Bluff.Pie('<%= j id %>', '400x300');
  g.title = '<%= j title %>';
  no_data_message = 'No issues';

  g.theme_pastel();
  g.set_background({colors: '#323a47'});
  g.font_color = '#fffefa';

  g.data("Resolved", <%= resolved %>, '#27ae60');
  g.data("Opened Issues", <%= opened %>, '#febf0f');
  g.data("Dismissed", <%= dismissed %>, '#e74c3c');
  g.draw();
})
</script>

app/views/shared/_task_buttons.html.erb
<div class='row'></div>
<div class="btn-group">
  <%= link_to_if(task.just_created, 'Edit', edit_task_path(task), class: 'btn btn-danger'){link_to 'Edit', "#", class: 'btn btn-danger', disabled: true} %>
  <% if task.just_created && current_user == task.user %>
    <%= link_to 'Start task', change_status_path(task, status: 'start'), class: 'btn btn-danger', method: :patch %>
    <%= link_to_if(task.has_no_user, 'Assign user', '#', class: 'btn btn-danger'){ link_to 'Reassign user', '#', class: 'btn btn-danger'} %>
    <%= link_to 'Cancel', change_status_path(task, status: 'dismiss'), class: 'btn btn-danger', method: :patch %>
  <% elsif task.in_progress && current_user == task.user %>
    <%= link_to 'Finish task', change_status_path(task, status: 'finish'), class: 'btn btn-danger', method: :patch %>
    <%= link_to 'Pause task', change_status_path(task, status: 'pause'), class: 'btn btn-danger', method: :patch %>
    <%= link_to 'Cancel', change_status_path(task, status: 'dismiss'), class: 'btn btn-danger', method: :patch %>
    <%= link_to_if(task.has_no_user, 'Assign user', '#', class: 'btn btn-danger'){ link_to 'Reassign user', '#', class: 'btn btn-danger'} %>
  <% elsif task.dismissed && (current_user.manager? || current_user.admin?) %>
    <%= link_to 'Activate', change_status_path(task, status: 'activate'), class: 'btn btn-danger', method: :patch %>
  <% elsif task.done %>
    <%= button_to 'Resolved', '#', disabled: true, class: 'btn btn-danger' %>
  <% elsif task.paused && current_user == task.user %>
    <%= link_to 'Continue', change_status_path(task, status: 'continue'), class: 'btn btn-danger', method: :patch %>
  <% end %>
</div>