config/routes.rb
Diploma::Application.routes.draw do
  devise_for :users

  root to: 'static#dashboard'

  resources :users do
    member do
      get :block
      get :unblock
      get :list_tasks
      get :show_statistics
    end
    collection do
      post :blocked
      get :blocked
    end
    resources :weekly_surveys
  end

  resources :projects do
  end
  resources :tasks

  #resources :project_montly_incomes
  delete 'users/:id/delete_avatar', to: 'users#delete_avatar', as: :delete_avatar
  delete 'projects/:id/delete_logo', to: 'project#delete_logo', as: :delete_logo
  patch 'task/:id/change_status', to: 'tasks#change_status', as: :change_status
  get 'blocked', to: 'static#blocked', as: :blocked
  get 'task_assign_adviser', to: 'static#task_adviser', as: :task_adviser
end

app/models/project.rb
class Project < ActiveRecord::Base
  require 'uri'
	# assosiations
	has_many :tasks, dependent: :delete_all
  has_many :users, through: :tasks
  has_many :action_logs, dependent: :delete_all
  has_many :project_monthly_incomes

	#attributes accessibility
	attr_accessible :name, :user_id, :description, :site, :logo

  has_attached_file :logo, :styles => { medium: "300x300>", thumb: "100x100>", small: "40x40>" }
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

	validates :name, presence: true, uniqueness: true
  validates :site, format: {with: URI.regexp(%w(http https))}

  def log_action(user, action, msg = '')
    action_logs.create! do |e|
      e.user = user
      e.action = action
      e.data = msg
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :load_collection
  before_filter :load_single, only: [:show, :edit, :destroy]

	def index
    @user = current_user
	end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new params[:project]
    if @project.save
      log_project @project, :created
      flash[:notice] = "Project was saved"
      render :index
    else
      render :new
    end
  end

  def show
    @user = current_user
    @action_logs = ActionLog.for_project(@project).first(15)
    @incomes = @project.project_monthly_incomes.pluck(:income_per_month)
    @months_count = (1..@project.project_monthly_incomes.pluck(:month).count)
    @months = @project.project_monthly_incomes.pluck(:month).map! do |m|
      m.strftime("%b %Y")
    end
    @expenses = []
    12.times { @expenses.push rand(5_000...10_000) } unless  @incomes.empty?
    @profit = @incomes.each_with_index.collect {|val, index| val - @expenses[index]}
    @month_hash = Hash[@months_count.zip @months]
    @created = @project.tasks.last_30_days
    @still_open = @created.still_open ? @created.still_open.count : 0
    @finished = @created.finished ? @created.finished.count : 0
    @dismissed = @created.dismissed ? @created.dismissed.count : 0
  end

  def edit
    render :edit
  end

  def update
    @project = Project.find params[:id]
    @project.update_attributes params[:project]
    if @project.save
      log_project @project, :updated
      flash[:notice] = "Successfuly updated"
      render :show
    else
      render :edit
    end
  end

  def delete_logo
    @project = Project.find params [:id]
    log_project @project, :deleted_project_logo

    @project.logo.destroy
    redirect_to project_path(@project)
  end

  private
  def load_collection
    @projects = Project.all.order('name ASC')
  end

  def load_single
    @project = Project.find params[:id]
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project_form.html.erb
  <div class="panel-body">
    <div class="col-md-7">
      <div class="panel panel-black">
        <div class="panel-heading">Logo</div>
        <div class="panel-body">
          <%= simple_form_for @project do |f| %>
          <% url = @project.logo.exists? ? @project.logo.url(:medium) : 'original/no-logo.png' %>
              <%= image_tag url, size: "300x300", alt: "NO logo", class: "img-thumbnail" %>
              <div class="input-group">
                <span class="btn btn-default btn-file">
                  <%= f.file_field :logo %>
                </span>
              </div>
              <p class="help-block">*Maximum resoution 300x300</p>
        </div>
      </div>
    </div>
    <div class="col-md-5">
      <%= f.error_notification %>
      <%= f.input :name, required: true %>
      <%= f.input :description, as: :text %>
      <%= f.input :site, as: :url, placeholder: 'http://' %>
      <br \>
      <%= f.button :submit %>
      <%= link_to 'Cancel', :back, class: 'btn btn-danger' %>
    <% end %>
    </div>

app/views/projects/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <ol class="breadcrumb">
      <li><%= link_to 'Dashboard', root_path %></li>
      <li><%= link_to 'Projects', projects_path %></li>
      <li class="active">Edit <%= @project.name %></li>
    </ol>
  </div>
  <%= render 'project_form'%>
</div>

app/views/projects/index.html.erb
<dl class="dl-horizontal panel panel-primary">
  <div class="panel-heading">Projects</div>
  <div class="panel-body">
    <%= link_to '+ new project', new_project_path, class: 'btn add-new-item' %>
    <% if @projects.any? %>
      <table class="table table-hover" id="projects-table">
        <th>Logo</th>
        <th>Name</th>
        <th>Site</th>
        <th>Description</th>
        <th>Users involved</th>
        <th>Actions</th>
        <% @projects.each do |project| %>
            <tr class="project-raw">
              <td>
               <% url = project.logo.exists? ? project.logo.url(:small) : 'original/no-logo.png' %>
                <%= image_tag url, size: "40x40", alt: "NO logo", class: "img-thumbnail" %>
              </td>
              <td><%= link_to project.name, project_path(project) %></td>
              <td>
                <%= link_to_if(project.site, project.site, project.site, target: '_blank'){'-'}   %>
              </td>
              <td><%= project.description ? project.description : '-' %></td>
              <td>
                <% if project.users.any? %>
                  <%= project.users.count %>
                  <br \>
                  <small>(<%= link_to 'list users', '#' %>)</small>
                <% else %>
                  -
                <% end %>
              </td>
              <td><%= link_to "edit", edit_project_path(project.id) %>
                <% if project.tasks.any? %>
                  <%= link_to "list tasks", tasks_path(project_id: project.id) %>
                <% end %>
              </td>
            </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</dl>

app/views/projects/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <ol class="breadcrumb">
      <li><%= link_to 'Dashboard', root_path %></li>
      <li><%= link_to 'Projects', projects_path %></li>
      <li class="active">New project</li>
    </ol>
  </div>
  <%= render 'project_form'%>
</div>

app/views/projects/show.html.erb
<div class="panel panel-black">
  <div class="panel-heading">
    <div class="media">
      <% url = @project.logo.exists? ? @project.logo.url(:thumb) : 'original/no-logo.png' %>
      <%= image_tag url, size: "100x100", alt: "NO logo", class: "img-responsive pull-left media-object" %>
      <div class="media-body">
        <h4 class="media-heading"><%= @project.name %></h4>
        <%= link_to_if(@project.site, @project.site, @project.site){} %>
        <br \>
        <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-info' %>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="col-md-6">
      <dl class="dl-horizontal panel panel-default">
        <div class="panel-heading">Summary details</div>
        <div class="panel-body">
            <blockquote><%= @project.description  %></blockquote>
        </div>
      </dl>
      <div class="panel panel-black">
        <div class="panel-heading"> Statistics </div>
        <div class="panel-body">
          <div class='well'>
            <h4>Issues: 30 Days</h4>
            <%= render partial: 'shared/statistics_graph', locals: { title: @project.name, opened: @still_open, resolved: @finished, dismissed: @dismissed, id: "#{@project.name}-last-30-days" } %>
          </div>
          <hr>
          <div class='well'>
            <h4>Profit: All time</h4>
            <%= render partial: 'shared/income_graph', locals: { title: 'Project income', month_hash: @month_hash, incomes: @incomes, expenses: @expenses, profit: @profit, id: "#{@project.name}-income" } %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <dl class="dl-horizontal panel panel-warning">
        <div class="panel-heading">Activity Stream <small>(last 10)</small></div>
          <div class="panel-body">
          <ul class="list-group">
            <% if (defined? @action_logs) && @action_logs.any? %>
              <% @action_logs.last(10).each do |log| %>
                <li class="list-group-item"><%= render partial: 'shared/action_log_box', locals: {action_log: log} %></li>
              <% end %>
              <%= link_to_if(@action_logs.size > 10, '<< Load more >>', "#", class: 'btn btn-warning btn-sm user-assign', style: 'width:100%;background-color:#e6a600 !important'){}%>
              <% else %>
              <p>Nothing happened</p>
            <% end %>
          </ul>
          </div>
        </div>
      </dl>
    </div>
  </div>
</div>